name: tagged-release
on:
  push:
    tags:
      - "v*"

permissions:
  id-token: "write"
  contents: "write"
env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build_and_release:
    runs-on: macos-14

    steps:
      - run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      - uses: actions/checkout@v5
        with:
          ref: master

      - name: Update manifest.json version
        uses: jossef/action-set-json-field@v2.2
        with:
          file: src/manifest.json
          field: version
          value: ${{ env.VERSION }}

      - name: Push files
        continue-on-error: true
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -am "release v${{ env.VERSION }}"
          git push

      - run: |
          gh release create ${{github.ref_name}} -d -F CURRENT_CHANGE.md -t ${{github.ref_name}}

      - uses: actions/setup-node@v5
        with:
          node-version: 20
      - run: npm ci

      - run: |
          gh release upload ${{github.ref_name}} build/chromium.zip

      - run: |
          gh release edit ${{github.ref_name}} --draft=false
